[tool.poetry]
name        = "spark-delta-minio-study"
version     = "1.0.0"
description = "Pipeline de dados com MinIO e Delta Lake — SATC"
authors     = [
    "Vanessa Ugioni",
    "Gabriel Muller",
    "Bettina da Silva",
]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python      = "^3.11"
pyspark     = "3.5.1"
delta-spark = "3.2.0"
jupyterlab  = "^4.0"
pandas      = "^2.0"
mkdocs = "^1.6.1"
mkdocs-material = "^9.7.6"
pymdown-extensions = "^10.0"
ghp-import = "^2.1.0"

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


